//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTRADOR
    {
        public int ID_ADMINISTRADOR { get; set; }
        public int ID_ROL { get; set; }
        public string CONTRASENA_ADM { get; set; }
        public string NOMBRE_ADM { get; set; }
        public string APELLIDO_ADM { get; set; }
        public string TELEFONO_ADM { get; set; }
        public string CORREO_ADM { get; set; }
    
        public virtual ROL ROL { get; set; }
    }
}
