//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECK_LIST
    {
        public int ID_FORMULARIO { get; set; }
        public string RUT_CLIENTE { get; set; }
        public string PREGUNTA_1 { get; set; }
        public string PREGUNTA_2 { get; set; }
        public string PREGUNTA_3 { get; set; }
        public string PREGUNTA_4 { get; set; }
        public string PREGUNTE_5 { get; set; }
        public string PREGUNTE_6 { get; set; }
        public string PREGUNTA_7 { get; set; }
        public string PREGUNTA_8 { get; set; }
        public string PREGUNTA_9 { get; set; }
        public string MEJORA_ACTIVIDAD { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
