//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.CHECK_LIST = new HashSet<CHECK_LIST>();
            this.CONTRATO = new HashSet<CONTRATO>();
            this.INTERACCION = new HashSet<INTERACCION>();
            this.REGISTRO_ALERTA = new HashSet<REGISTRO_ALERTA>();
            this.SOLICITUD = new HashSet<SOLICITUD>();
        }
    
        public string RUT_CLIENTE { get; set; }
        public int ID_ROL { get; set; }
        public string CONTRASENA_CLIENTE { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string APELLIDO_CLIENTE { get; set; }
        public string NOMBRE_EMPRESA { get; set; }
        public string RUBRO_EMPRESA { get; set; }
        public string TELEFONO_CLIENTE { get; set; }
        public string CORREO_CLIENTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECK_LIST> CHECK_LIST { get; set; }
        public virtual ROL ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO> CONTRATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INTERACCION> INTERACCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_ALERTA> REGISTRO_ALERTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD> SOLICITUD { get; set; }
    }
}
