//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        public int ID_CONTRATO { get; set; }
        public string RUT_CLIENTE { get; set; }
        public int ESTADO_CONTRATO { get; set; }
        public System.DateTime FECHA_INICIO_CONTRATO { get; set; }
        public System.DateTime FECHA_TERMINO_CONTRATO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ESTADO_CONTRATO ESTADO_CONTRATO1 { get; set; }
    }
}
