//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_ACTIVIDAD
    {
        public int REGISTRO_ACTIVIDAD { get; set; }
        public int ID_ACTIVIDAD { get; set; }
        public int ID_PROFESIONAL { get; set; }
        public string UBICACION { get; set; }
        public System.DateTime FECHA_ACTIVIDAD { get; set; }
        public Nullable<int> ASISTENTE { get; set; }
        public string MATERIAL { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ACTIVIDAD ACTIVIDAD { get; set; }
        public virtual PROFESIONAL PROFESIONAL { get; set; }
    }
}
