//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERACCION
    {
        public int ID_INTERACCION { get; set; }
        public string RUT_CLIENTE { get; set; }
        public System.DateTime FECHA_INTERACCION { get; set; }
        public int ESTADO_INTERACCION { get; set; }
        public int ID_TIPO_INTERACCION { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ESTADO_INTERACCION ESTADO_INTERACCION1 { get; set; }
        public virtual TIPO_INTERACCION TIPO_INTERACCION { get; set; }
    }
}
