//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTIVIDAD> ACTIVIDAD { get; set; }
        public virtual DbSet<ADMINISTRADOR> ADMINISTRADOR { get; set; }
        public virtual DbSet<CHECK_LIST> CHECK_LIST { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<CONTRATO> CONTRATO { get; set; }
        public virtual DbSet<DETALLE_ACTIVIDAD> DETALLE_ACTIVIDAD { get; set; }
        public virtual DbSet<ESTADO_ALERTA> ESTADO_ALERTA { get; set; }
        public virtual DbSet<ESTADO_CONTRATO> ESTADO_CONTRATO { get; set; }
        public virtual DbSet<ESTADO_INTERACCION> ESTADO_INTERACCION { get; set; }
        public virtual DbSet<ESTADO_SOLICITUD> ESTADO_SOLICITUD { get; set; }
        public virtual DbSet<INTERACCION> INTERACCION { get; set; }
        public virtual DbSet<PAGO> PAGO { get; set; }
        public virtual DbSet<PROFESIONAL> PROFESIONAL { get; set; }
        public virtual DbSet<PUNTAJE> PUNTAJE { get; set; }
        public virtual DbSet<REGISTRO_ALERTA> REGISTRO_ALERTA { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<SOLICITUD> SOLICITUD { get; set; }
        public virtual DbSet<TIPO_ALERTA> TIPO_ALERTA { get; set; }
        public virtual DbSet<TIPO_INTERACCION> TIPO_INTERACCION { get; set; }
        public virtual DbSet<VALORACIONES> VALORACIONES { get; set; }
    }
}
