//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFESIONAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROFESIONAL()
        {
            this.DETALLE_ACTIVIDAD = new HashSet<DETALLE_ACTIVIDAD>();
            this.VALORACIONES = new HashSet<VALORACIONES>();
        }
    
        public int ID_PROFESIONAL { get; set; }
        public int ID_ROL { get; set; }
        public int ID_ACTIVIDAD { get; set; }
        public string CONTRASENA_PRO { get; set; }
        public string NOMBRE_PRO { get; set; }
        public string APELLIDO_PRO { get; set; }
        public string TELEFONO_PRO { get; set; }
        public string CORREO_PRO { get; set; }
        public Nullable<byte> CALIFICACION { get; set; }
    
        public virtual ACTIVIDAD ACTIVIDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ACTIVIDAD> DETALLE_ACTIVIDAD { get; set; }
        public virtual ROL ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VALORACIONES> VALORACIONES { get; set; }
    }
}
