//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_ALERTA
    {
        public int ID_ALERTA { get; set; }
        public int TIPO_ALERTA { get; set; }
        public string RUT_CLIENTE { get; set; }
        public System.DateTime FECHA_ALERTA { get; set; }
        public string DESCRIPCION_ALERTA { get; set; }
        public int ESTADO_ALERTA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ESTADO_ALERTA ESTADO_ALERTA1 { get; set; }
        public virtual TIPO_ALERTA TIPO_ALERTA1 { get; set; }
    }
}
