//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD
    {
        public int ID_SOLICITUD { get; set; }
        public string RUT_CLIENTE { get; set; }
        public string UBICACION_SOLICITUD { get; set; }
        public System.DateTime FECHA_SOLICITUD { get; set; }
        public System.DateTime FECHA_RESOLUCION { get; set; }
        public string PROFESIONAL_ASIGNADO { get; set; }
        public string MENSAJE { get; set; }
        public Nullable<int> ASISTENTE_SOLICITUD { get; set; }
        public int ESTADO_SOLICITUD { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ESTADO_SOLICITUD ESTADO_SOLICITUD1 { get; set; }
    }
}
